#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

test -f $sysresources    && xrdb -merge  $sysresources
test -f $sysmodmap       && xmodmap      $sysmodmap
test -f "$userresources" && xrdb -merge "$userresources"
test -f "$usermodmap"    && xmodmap     "$usermodmap"


# start some nice programs
test $(which gpg-agent) && eval $(gpg-agent --daemon)

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

setxkbmap -option caps:escape		        # run the remaps script, switching caps/esc and more; check it for more info
mpd &			                        # music player daemon-you might prefer it as a service though
feh --bg-center ~/.local/share/wall.jpg &	# set the background with the `setbg` script
xcompmgr &	                	        # xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
redshift -c $HOME/.config/redshift/config &

# source machine- and uname-specific xinitrcs
xinitcfg="$HOME/.config/xinit"
test -f "$xinitcfg/u/$(uname)"       && . "$xinitcfg/u/$(uname)"
test -f "$xinitcfg/host/$(hostname)" && . "$xinitcfg/host/$(hostname)"

# /usr/local/bin/dwm 2>>.dwm_log &

while :; do
		ssh-agent dwm || break
		done

# exit X when dwmstatus (or failsafe xterm) is killed
if [ $(which slstatus) ]; then
    slstatus
elif [ $(which dwmblocks) ]; then
    dwmblocks
elif [ $(which st) ]; then
    st
elif [ $(which urxvt) ]; then
    urxvt
elif [ $(which uxterm) ]; then
    uxterm -ls -T Failsafe -geometry 80x24-0-0
elif [ $(which rxvt) ]; then
    rxvt
elif [ $(which xterm) ]; then
    xterm -ls -T Failsafe -geometry 80x24-0-0
elif [ $(which gnome-terminal) ]; then
    gnome-terminal
fi
