#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

test -f $sysresources    && xrdb -merge  $sysresources
test -f $sysmodmap       && xmodmap      $sysmodmap
test -f "$userresources" && xrdb -merge "$userresources"
test -f "$usermodmap"    && xmodmap     "$usermodmap"


# start some nice programs
test $(which gpg-agent) && eval $(gpg-agent --daemon)

remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
# xcompmgr &		# xcompmgr for transparency
picom &   # using picom instead of picom
$STATUSBAR &		# script for updating the status bar
dunst &			# dunst for notifications
sxhkd -m 1 &		# Bind keys with sxhkd
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
mpd-module-update &	# Check for when to update the mpd module

# source machine- and uname-specific xinitrcs
xinitcfg="$HOME/.config/xinit"
test -f "$xinitcfg/u/$(uname)"       && . "$xinitcfg/u/$(uname)"
test -f "$xinitcfg/host/$(hostname)" && . "$xinitcfg/host/$(hostname)"

# /usr/local/bin/dwm 2>>.dwm_log &

while :; do
		ssh-agent dwm || break
		done

# exit X when dwmstatus (or failsafe xterm) is killed
if [ $(which slstatus) ]; then
    slstatus
elif [ $(which dwmstatus) ]; then
    dwmstatus
elif [ $(which st) ]; then
    st
elif [ $(which urxvt) ]; then
    urxvt
elif [ $(which uxterm) ]; then
    uxterm -ls -T Failsafe -geometry 80x24-0-0
elif [ $(which rxvt) ]; then
    rxvt
elif [ $(which xterm) ]; then
    xterm -ls -T Failsafe -geometry 80x24-0-0
elif [ $(which gnome-terminal) ]; then
    gnome-terminal
fi
